// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evumygptgyupxpdqcspd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dW15Z3B0Z3l1cHhwZHFjc3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDExMTIsImV4cCI6MjA2NDAxNzExMn0.9QL4IZdm82OF3xTNlYlx5-Tu1YGWLthJx-a6tO5j3U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);